#Configuration

#Messages

messages:
  joinbc: "ciccio1"
  privatemsg:
    - "ciccio2"
    - "ciccioriccio"
  repetemessages:
    - "Bastardo"
    - "Vengo da reggio"
    - "Emilia"

playerhider:
  hidetitle: "&c&lPLAYER NASCOSTI"
  showtitle: "&b&lPLAYER VISIBILI"

book:
  author: "sburra"
  title: "cacca"
  text:
    - "&bciccio 1 \n &cciccionero"